### ISSUE TITLE
Stuck on "loading" after use button is clicked

### ISSUE THREAD

**Issue by zoomtronic** [jorisdugue/h5p-bundle#2]
Hi,
Sorry to bother you again,

The documentation is not up to date but i managed to make it work partially.

I can install h5p libraries, but when i click "use" the "Loading, please wait..." is stuck..

I have two errors

First in Chrome

`Ajax request failed`

And in my Php logs

```
CRITI| PHP    Uncaught Error: Call to a member function getRepository() on null 

|CRITI| REQUES Uncaught PHP Exception Error: "Call to a member function getRepository() on null" at /Users/zoomtronic/Desktop/Projets/www/H5Ptest/h5ptestsf5/vendor/jorisdugue/h5p-bundle/Event/H5PEvents.php line 75 

|ERROR| SERVER GET  (500) /h5p/ajax/libraries/?machineName=H5P.Audio&majorVersion=1&minorVersion=4 
```

In H5PEvents.php line 75 its written, 
`$this->em->getRepository("StuditH5PBundle:Counters")`

But there is no CounterRepository in the Entity folder. I think that's not why the ajax call failed earlier.. is it working well on your side ?

p.s: i tried with a new SF5 project

**Comment by jorisdugue** [comment]
Hello,
The problem is solved for the moment I deactivated this part (following the next update of H5P which will arrive soon) but for the moment it is clearly not useful (unless you intend to make statistics?).

I have deployed and updated the documentation a bit. If you need more documentation don't hesitate

**Comment by zoomtronic** [comment]
Hi,
I've just update the package and for now its working great !
